name: Manual Trigger

on:
  workflow_dispatch:
    inputs:

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      - run: npm start
        env:
          MODE: manual
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          DATABASE_ID_BACKLOG: ${{ secrets.DATABASE_ID_BACKLOG }}
          DATABASE_ID_SPRINT_SUMMARY: ${{ secrets.DATABASE_ID_SPRINT_SUMMARY }}
          DATABASE_ID_DAILY_SUMMARY: ${{ secrets.DATABASE_ID_DAILY_SUMMARY }}
          BACKLOG_PROPERTY_SPRINT: ${{ secrets.BACKLOG_PROPERTY_SPRINT }}
          BACKLOG_PROPERTY_EXCLUDE_STATUS_PATTERN: ${{ secrets.BACKLOG_PROPERTY_EXCLUDE_STATUS_PATTERN }}
          BACKLOG_PROPERTY_STORY_POINTS: ${{ secrets.BACKLOG_PROPERTY_STORY_POINTS }}
      - name: Commit burndown chart
        run: |
          git config --local user.email ${{ secrets.GH_USER_EMAIL }}
          git config --local user.name "supplyally-bot"
          git add ./out
          git commit -m "run: upload new burndown chart"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
